apiVersion: apps/v1
kind: Deployment
metadata:
  name: memespread
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memespread
  template:
    metadata:
      labels:
        app: memespread
    spec:
      initContainers:
        - name: wait-for-clickhouse
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until wget -q -O- http://clickhouse:8123/ping; do echo waiting for clickhouse; sleep 2; done;",
            ]
      containers:
        - name: memespread
          image: memespread:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: backend
            - containerPort: 3000
              name: frontend
          env:
            - name: CLICKHOUSE_URL
              value: "http://clickhouse:8123"
            - name: HELIUS_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: HELIUS_API_KEY
            - name: RUST_LOG
              value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: memespread
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: backend
      name: backend
    - port: 3000
      targetPort: frontend
      name: frontend
  selector:
    app: memespread
